#!/bin/sh
# [Gedit Tool]
# Name=Browse Home Folder
# Shortcut=<Primary><Shift><Alt>h
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=nothing

/usr/bin/nemo --no-desktop $GEDIT_FILE_BROWSER_ROOT
