#!/bin/sh
# [Gedit Tool]
# Name=Browse as Thioshp
# Shortcut=<Primary><Shift><Alt>t
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=nothing

/usr/bin/nemo --no-desktop $GEDIT_CURRENT_DOCUMENT_DIR
